export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'; //estar logeado
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UI_RESET_ERROR = 'UI_RESET_ERROR' //borrar errores

export const AUTH_REMEMBER_PASSWORD_REQUEST = 'AUTH_REMEMBER_PASSWORD_REQUEST'
export const AUTH_REMEMBER_PASSWORD_SUCCESS = 'AUTH_REMEMBER_PASSWORD_SUCCESS'
export const AUTH_REMEMBER_PASSWORD_FAILURE = 'AUTH_REMEMBER_PASSWORD_FAILURE'


export const UI_SIGNUP_REQUEST = 'UI_SIGNUP_REQUEST'; 
export const UI_SIGNUP_SUCCESS = 'UI_SIGNUP_SUCCESS';
export const UI_SIGNUP_FAILURE = 'UI_SIGNUP_FAILURE';

// Travels actions.types:

export const CREATE_TRAVEL_REQUEST = 'CREATE_TRAVEL_REQUEST';
export const CREATE_TRAVEL_SUCCESS = 'CREATE_TRAVEL_SUCCESS';
export const CREATE_TRAVEL_FAILURE = 'CREATE_TRAVEL_FAILURE';

export const DELETE_TRAVEL_REQUEST = 'DELETE_TRAVEL_REQUEST';
export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS';
export const DELETE_TRAVEL_FAILURE = 'DELETE_TRAVEL_FAILURE';

export const ADD_TRAVEL_REQUEST = 'ADD_TRAVEL_REQUEST';
export const ADD_TRAVEL_SUCCESS = 'ADD_TRAVEL_SUCCESS';
export const ADD_TRAVEL_FAILURE = 'ADD_TRAVEL_FAILURE';

export const FETCH_TRAVELS_REQUEST = 'FETCH_TRAVELS_REQUEST';
export const FETCH_TRAVELS_SUCCESS = 'FETCH_TRAVELS_SUCCESS';
export const FETCH_TRAVELS_FAILURE = 'FETCH_TRAVELS_FAILURE';